AWSTemplateFormatVersion: '2010-09-09'
Description: 'wgot-listeners-data

  SAM template for service to track web radio listener stats

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  IcecastDataFunctionIamRole:
    Description: Implicit IAM Role created for icecast scrape function
    Value:
      Fn::GetAtt:
      - IcecastScrapeFunction
      - Arn
  IcecastScrapeFunction:
    Description: Function to scrape icecast data from pacifica
    Value:
      Fn::GetAtt:
      - IcecastScrapeFunction
      - Arn
Resources:
  IcecastScrapeFunction:
    Properties:
      CodeUri: s3://mplit-wgot-data/7f9a1848941ef7434d5a79427bfaced4
      Environment:
        Variables:
          StatsTable:
            Ref: ListenerTable
      Events: null
      Handler: app.lambda_handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  ListenerTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: timestamp
        AttributeType: N
      - AttributeName: listeners
        AttributeType: N
      KeySchema:
      - AttributeName: timestamp
        KeyType: HASH
      - AttributeName: listeners
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  TimerEvent:
    DependsOn: IcecastScrapeFunction
    Properties:
      ScheduleExpression: rate(5 minutes)
      Targets:
      - Arn:
          Fn::GetAtt:
          - IcecastScrapeFunction
          - Arn
        Id: IcecastScrapeFunction
    Type: AWS::Events::Rule
Transform: AWS::Serverless-2016-10-31
